# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, priorities: [ 'json', 'html', '*/*' ], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
